version: "3.8"

services:
  flask:
    build: ./app
    container_name: flask_app
    restart: always

  nginx:
    build: ./nginx
    container_name: nginx_proxy
    ports:
      - "80:80"
    depends_on:
      - flask
